// data.jsx — sample collection
// All data inline; no fetches. Authoritative-feeling cert IDs and telemetry.

const COLLECTION = [
  {
    id: "PG-2026-0F1A4C",
    name: "Charizard",
    set: "Base Set",
    number: "4/102",
    year: 1999,
    variant: "Holo · Unlimited",
    final: 9.0,
    lower: 8.6, upper: 9.3, conf: 0.91,
    centering: 9.0, corners: 9.5, edges: 8.5, surface: 9.0,
    auth: "authentic", authConf: 0.97,
    pop: { total: 47, rank: 3, chrono: 12 },
    captured: "2026-04-22 14:08",
    color: "#f97316",
    glyph: "🜂",
    detectors: [
      { k: "rosette", s: 0.94, c: 0.92, v: "authentic" },
      { k: "holo-parallax", s: 0.96, c: 0.93, v: "authentic" },
      { k: "knn-reference", s: 0.91, c: 0.88, v: "authentic" },
      { k: "typography", s: 0.99, c: 0.94, v: "authentic" },
      { k: "substrate", s: 0.93, c: 0.81, v: "authentic" },
      { k: "embedding", s: 0.95, c: 0.86, v: "authentic" },
      { k: "cielab-color", s: 0.92, c: 0.84, v: "authentic" },
    ],
    defects: [
      { region: "edge-bottom", severity: "minor", note: "Whitening, 4.2mm" },
      { region: "corner-tl", severity: "ok", note: "Within tolerance" },
      { region: "surface", severity: "minor", note: "Print line, lower-left quadrant" },
    ],
  },
  {
    id: "PG-2026-3B92E7",
    name: "Black Lotus",
    set: "Alpha",
    number: "232/295",
    year: 1993,
    variant: "Power Nine",
    final: 8.5,
    lower: 8.1, upper: 8.9, conf: 0.88,
    centering: 8.0, corners: 9.0, edges: 8.5, surface: 8.5,
    auth: "authentic", authConf: 0.99,
    pop: { total: 12, rank: 4, chrono: 2 },
    captured: "2026-04-19 10:31",
    color: "#a3a3a3",
    glyph: "✦",
    detectors: [],
    defects: [],
  },
  {
    id: "PG-2026-7D40A9",
    name: "Pikachu Illustrator",
    set: "Promo",
    number: "—",
    year: 1998,
    variant: "CoroCoro Comic",
    final: null,
    lower: null, upper: null, conf: 0.42,
    centering: 9.5, corners: null, edges: 8.0, surface: null,
    auth: "suspicious", authConf: 0.68,
    pop: { total: 1, rank: 1, chrono: 1 },
    captured: "2026-05-02 22:14",
    color: "#fbbf24",
    glyph: "⚡",
    detectors: [],
    defects: [],
    flag: "Preliminary — corners + surface heads not trained",
  },
  {
    id: "PG-2026-22A1B0",
    name: "Blue-Eyes White Dragon",
    set: "LOB 1st Ed.",
    number: "001",
    year: 2002,
    variant: "Ultra Rare",
    final: 9.5,
    lower: 9.2, upper: 9.7, conf: 0.93,
    centering: 9.5, corners: 9.5, edges: 9.5, surface: 9.5,
    auth: "authentic", authConf: 0.98,
    pop: { total: 28, rank: 1, chrono: 7 },
    captured: "2026-04-28 09:02",
    color: "#60a5fa",
    glyph: "❄",
    detectors: [],
    defects: [],
  },
  {
    id: "PG-2026-994FE2",
    name: "Mickey Mantle",
    set: "Topps",
    number: "#311",
    year: 1952,
    variant: "Rookie",
    final: 6.5,
    lower: 5.9, upper: 7.1, conf: 0.81,
    centering: 6.0, corners: 6.5, edges: 7.0, surface: 6.5,
    auth: "authentic", authConf: 0.91,
    pop: { total: 4, rank: 2, chrono: 4 },
    captured: "2026-04-15 16:44",
    color: "#dc2626",
    glyph: "♦",
    detectors: [],
    defects: [],
  },
  {
    id: "PG-2026-1FD3C8",
    name: "Umbreon VMAX",
    set: "Evolving Skies",
    number: "215/203",
    year: 2021,
    variant: "Alt Art",
    final: 9.5,
    lower: 9.3, upper: 9.7, conf: 0.94,
    centering: 9.5, corners: 9.5, edges: 9.5, surface: 9.5,
    auth: "authentic", authConf: 0.99,
    pop: { total: 89, rank: 14, chrono: 23 },
    captured: "2026-05-03 11:07",
    color: "#7c3aed",
    glyph: "☾",
    detectors: [],
    defects: [],
  },
  {
    id: "PG-2026-44B102",
    name: "Liliana of the Veil",
    set: "Innistrad",
    number: "105",
    year: 2011,
    variant: "Mythic",
    final: 8.0,
    lower: 7.5, upper: 8.4, conf: 0.85,
    centering: 7.5, corners: 8.5, edges: 8.0, surface: 8.0,
    auth: "authentic", authConf: 0.95,
    pop: { total: 18, rank: 6, chrono: 9 },
    captured: "2026-04-20 19:30",
    color: "#262626",
    glyph: "✶",
    detectors: [],
    defects: [],
  },
  {
    id: "PG-2026-08FF55",
    name: "Lebron James",
    set: "Topps Chrome",
    number: "#111",
    year: 2003,
    variant: "Rookie Refractor",
    final: 9.0,
    lower: 8.6, upper: 9.3, conf: 0.89,
    centering: 9.0, corners: 9.0, edges: 9.0, surface: 9.0,
    auth: "authentic", authConf: 0.96,
    pop: { total: 33, rank: 5, chrono: 11 },
    captured: "2026-04-12 13:18",
    color: "#facc15",
    glyph: "★",
    detectors: [],
    defects: [],
  },
  {
    id: "PG-2026-7E2D1A",
    name: "Lugia",
    set: "Neo Genesis",
    number: "9/111",
    year: 2000,
    variant: "Holo 1st Ed.",
    final: 8.5,
    lower: 8.0, upper: 8.9, conf: 0.86,
    centering: 8.0, corners: 9.0, edges: 8.5, surface: 8.5,
    auth: "authentic", authConf: 0.95,
    pop: { total: 22, rank: 8, chrono: 14 },
    captured: "2026-04-25 21:55",
    color: "#e0e7ff",
    glyph: "✧",
    detectors: [],
    defects: [],
  },
  {
    id: "PG-2026-AA3309",
    name: "Mox Ruby",
    set: "Beta",
    number: "—",
    year: 1993,
    variant: "Power Nine",
    final: 7.0,
    lower: 6.4, upper: 7.5, conf: 0.78,
    centering: 6.5, corners: 7.0, edges: 7.5, surface: 7.0,
    auth: "authentic", authConf: 0.97,
    pop: { total: 6, rank: 5, chrono: 5 },
    captured: "2026-03-30 08:12",
    color: "#ef4444",
    glyph: "◆",
    detectors: [],
    defects: [],
  },
  {
    id: "PG-2026-560BC1",
    name: "Mew",
    set: "Promo",
    number: "8",
    year: 2000,
    variant: "Ancient Mew",
    final: 9.0,
    lower: 8.7, upper: 9.2, conf: 0.92,
    centering: 9.0, corners: 9.0, edges: 9.0, surface: 9.0,
    auth: "authentic", authConf: 0.96,
    pop: { total: 51, rank: 18, chrono: 19 },
    captured: "2026-04-08 17:22",
    color: "#f472b6",
    glyph: "❀",
    detectors: [],
    defects: [],
  },
  {
    id: "PG-2026-30E8A2",
    name: "Dark Magician",
    set: "SDY",
    number: "006",
    year: 2002,
    variant: "Ultra Rare",
    final: 8.0,
    lower: 7.5, upper: 8.4, conf: 0.84,
    centering: 7.5, corners: 8.0, edges: 8.5, surface: 8.0,
    auth: "authentic", authConf: 0.94,
    pop: { total: 14, rank: 7, chrono: 17 },
    captured: "2026-04-02 12:04",
    color: "#7e22ce",
    glyph: "✺",
    detectors: [],
    defects: [],
  },
];

// Stats — derived, but pre-computed for clean readability
const STATS = {
  total: 12,
  byScheme: { psa: 12 },
  avgFinal: 8.4,
  flagged: 1,
  highest: { id: "PG-2026-22A1B0", grade: 9.5 },
  pendingHeads: 2,
  detectorsActive: 7,
  catalogSize: "1,284,412",
  lastFlywheel: "06:00 UTC",
  modelVersions: {
    "centering": "v0.4.1",
    "edges": "v0.3.0-mad",
    "corners": "stub",
    "surface": "stub",
    "ident": "dinov2-vitb14",
    "detect": "yolo11s-seg",
  },
};

// 8-shot capture protocol
const SHOT_PROTOCOL = [
  { k: "front",   t: "Front",       d: "Centered, dewarp anchor" },
  { k: "back",    t: "Back",        d: "Reverse face, watermark" },
  { k: "tl",      t: "Corner · TL", d: "Macro, top-left" },
  { k: "tr",      t: "Corner · TR", d: "Macro, top-right" },
  { k: "bl",      t: "Corner · BL", d: "Macro, bottom-left" },
  { k: "br",      t: "Corner · BR", d: "Macro, bottom-right" },
  { k: "flash",   t: "Flash",       d: "Paired-flash for substrate" },
  { k: "tilt",    t: "Tilt",        d: "30° for holographic-parallax" },
];

window.COLLECTION = COLLECTION;
window.STATS = STATS;
window.SHOT_PROTOCOL = SHOT_PROTOCOL;
