"use client";

/**
 * Cert share card — the social-proof artifact at the top of `/cert/[id]`.
 *
 * TAG Grading's digital cert leans on a cert# + QR code as the
 * "stickiness" hook: anyone with the QR can scan-to-verify. We have no
 * physical slab, so the digital cert IS the artifact. This component
 * gives users:
 *
 *   - A QR code encoding the canonical cert URL (scan from a phone).
 *   - The cert ID rendered in a copyable monospace pill.
 *   - A native Web Share API button (mobile) with a graceful fallback
 *     dropdown for desktop browsers (Twitter intent, Discord-via-mail,
 *     and clipboard-copy).
 *   - A "Save image" button that pulls the route-level OG image PNG —
 *     reusing the same render, no html-to-image dependency required.
 *   - A "Print / PDF" button that opens the dedicated print-friendly
 *     view in a new tab.
 *
 * Marked "use client" because:
 *   - `navigator.clipboard.writeText` is only available in browsers.
 *   - `navigator.share` likewise.
 *   - We use `useState` for the dropdown + copy-toast.
 *
 * Props are pre-fetched server-side and passed down — the parent server
 * component already calls `fetchCertificate`, so we don't double-fetch.
 */

import { QRCodeSVG } from "qrcode.react";
import { useState } from "react";

export type CertShareCardProps = {
  certId: string;
  /** Canonical cert URL — server-built so the QR encodes the right host. */
  certUrl: string;
  /** Pre-formatted card name for the share intent (e.g. tweet body). */
  cardName: string;
  /** Final grade text already formatted (e.g. "8.5" or "—") for sharing. */
  finalGradeLabel: string;
};

const REVIEW_EMAIL = "reviews@grader.app";

export default function CertShareCard({
  certId,
  certUrl,
  cardName,
  finalGradeLabel,
}: CertShareCardProps) {
  const [copied, setCopied] = useState<"id" | "url" | null>(null);
  const [shareMenuOpen, setShareMenuOpen] = useState(false);

  const shareText = `${cardName} — graded ${finalGradeLabel} via Project Grader`;

  async function copyText(value: string, kind: "id" | "url") {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(kind);
      setTimeout(() => setCopied(null), 1600);
    } catch {
      // Older browsers / insecure contexts: fall back to a no-op +
      // toast that prompts manual copy. Better than crashing.
      setCopied(null);
    }
  }

  async function onShare() {
    const data: ShareData = {
      title: `Cert ${certId}`,
      text: shareText,
      url: certUrl,
    };
    // Web Share API — available on iOS Safari, modern Chrome on Android,
    // and Edge/Chrome on Windows 10+. Falls back to the dropdown.
    if (typeof navigator !== "undefined" && "share" in navigator) {
      try {
        await navigator.share(data);
        return;
      } catch {
        // User cancelled, or share failed — drop into dropdown.
      }
    }
    setShareMenuOpen((v) => !v);
  }

  function onPrint() {
    // Opens the print-friendly view; that page auto-triggers
    // window.print() on load (see /cert/[id]/print/page.tsx).
    if (typeof window !== "undefined") {
      window.open(`/cert/${certId}/print`, "_blank", "noopener,noreferrer");
    }
  }

  function onSaveImage() {
    // The OG image is already a 1200x630 PNG generated by Next.js's
    // file-based metadata image route. Opening it in a new tab lets
    // the user right-click → save (works on every desktop browser
    // without a html-to-image dep, ~30kb saved).
    if (typeof window !== "undefined") {
      window.open(
        `/cert/${certId}/opengraph-image`,
        "_blank",
        "noopener,noreferrer",
      );
    }
  }

  const twitterIntent = `https://twitter.com/intent/tweet?text=${encodeURIComponent(
    shareText,
  )}&url=${encodeURIComponent(certUrl)}`;
  const discordMailto = `mailto:?subject=${encodeURIComponent(
    `Cert ${certId}`,
  )}&body=${encodeURIComponent(`${shareText}\n${certUrl}`)}`;

  return (
    <section
      data-testid="cert-share-card"
      className="flex flex-col gap-4 rounded-2xl border border-zinc-800 bg-zinc-900/40 p-5 sm:flex-row sm:items-center sm:gap-6"
    >
      <div className="flex shrink-0 items-center justify-center rounded-xl bg-white p-3">
        <QRCodeSVG
          value={certUrl}
          size={120}
          level="M"
          aria-label="QR code linking to cert URL"
        />
      </div>
      <div className="flex flex-1 flex-col gap-3">
        <div className="flex flex-col gap-1">
          <p className="text-xs uppercase tracking-widest text-lime-500">
            Cert ID
          </p>
          <button
            type="button"
            onClick={() => copyText(certId, "id")}
            className="self-start break-all rounded-md bg-zinc-800/80 px-2 py-1 text-left font-mono text-xs text-zinc-100 hover:bg-zinc-800"
            aria-label="Copy cert ID"
          >
            {certId}
            <span className="ml-2 text-zinc-500">
              {copied === "id" ? "copied" : "click to copy"}
            </span>
          </button>
        </div>
        <div className="flex flex-wrap gap-2">
          <button
            type="button"
            onClick={() => copyText(certUrl, "url")}
            className="rounded-lg border border-zinc-700 px-3 py-1.5 text-xs text-zinc-200 hover:border-zinc-500"
          >
            {copied === "url" ? "URL copied" : "Copy cert URL"}
          </button>
          <div className="relative">
            <button
              type="button"
              onClick={onShare}
              className="rounded-lg border border-lime-500/50 bg-lime-500/10 px-3 py-1.5 text-xs font-medium text-lime-300 hover:border-lime-400"
              aria-haspopup="menu"
              aria-expanded={shareMenuOpen}
            >
              Share
            </button>
            {shareMenuOpen && (
              <div
                role="menu"
                className="absolute left-0 top-full z-10 mt-1 flex flex-col gap-1 rounded-lg border border-zinc-700 bg-zinc-900 p-2 text-xs shadow-lg"
              >
                <a
                  role="menuitem"
                  href={twitterIntent}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="rounded px-2 py-1 text-zinc-200 hover:bg-zinc-800"
                >
                  Share on X / Twitter
                </a>
                <a
                  role="menuitem"
                  href={discordMailto}
                  className="rounded px-2 py-1 text-zinc-200 hover:bg-zinc-800"
                >
                  Email / Discord
                </a>
                <button
                  type="button"
                  role="menuitem"
                  onClick={() => {
                    void copyText(certUrl, "url");
                    setShareMenuOpen(false);
                  }}
                  className="rounded px-2 py-1 text-left text-zinc-200 hover:bg-zinc-800"
                >
                  Copy link to clipboard
                </button>
              </div>
            )}
          </div>
          <button
            type="button"
            onClick={onPrint}
            className="rounded-lg border border-zinc-700 px-3 py-1.5 text-xs text-zinc-200 hover:border-zinc-500"
          >
            Print / PDF
          </button>
          <button
            type="button"
            onClick={onSaveImage}
            className="rounded-lg border border-zinc-700 px-3 py-1.5 text-xs text-zinc-200 hover:border-zinc-500"
          >
            Save as image
          </button>
        </div>
      </div>
    </section>
  );
}

/**
 * Stub CTA: future task wires this to a real /reviews route. For now,
 * a `mailto:` keeps the friction-low option available without standing
 * up an inbox-routing endpoint. Email is hardcoded as a constant so
 * it's grep-able when the real backend lands.
 */
export function ReviewRequestLink({ certId }: { certId: string }) {
  const href = `mailto:${REVIEW_EMAIL}?subject=${encodeURIComponent(
    `Cert ${certId} review request`,
  )}`;
  return (
    <aside className="rounded-xl border border-zinc-800 bg-zinc-900/30 p-4 text-sm text-zinc-400">
      <p className="mb-2 text-zinc-200">Disagree with this grade?</p>
      <p className="mb-3 text-xs">
        Request a manual review and a human grader will re-examine the
        evidence trail.
      </p>
      <a
        href={href}
        className="inline-block rounded-lg border border-zinc-700 px-3 py-1.5 text-xs text-zinc-200 hover:border-zinc-500"
      >
        Request manual review
      </a>
    </aside>
  );
}
